# Generated by Django 5.2.6 on 2025-10-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_produto_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.URLField(blank=True, help_text='URL da imagem do produto', null=True),
        ),
    ]
